const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"家政服务类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryJiazhengfuwu"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"家政服务管理",
                        "menuJump":"列表",
                        "tableName":"jiazhengfuwu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"家政服务评价管理",
                        "menuJump":"列表",
                        "tableName":"jiazhengfuwuCommentback"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"家政服务留言管理",
                        "menuJump":"列表",
                        "tableName":"jiazhengfuwuLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"家政服务收藏管理",
                        "menuJump":"列表",
                        "tableName":"jiazhengfuwuCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "订单",
                            "查看",
                            "删除"
                        ],
                        "menu":"家政服务订单管理",
                        "menuJump":"列表",
                        "tableName":"jiazhengfuwuOrder"
                    }
                ],
                "menu":"家政服务管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"员工管理",
                        "menuJump":"列表",
                        "tableName":"yuangong"
                    }
                ],
                "menu":"员工管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"家政服务管理",
                        "menuJump":"列表",
                        "tableName":"jiazhengfuwu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"家政服务订单管理",
                        "menuJump":"列表",
                        "tableName":"jiazhengfuwuOrder"
                    }
                ],
                "menu":"家政服务管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"员工",
        "tableName":"yuangong"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"家政服务管理",
                        "menuJump":"列表",
                        "tableName":"jiazhengfuwu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"家政服务评价管理",
                        "menuJump":"列表",
                        "tableName":"jiazhengfuwuCommentback"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"家政服务留言管理",
                        "menuJump":"列表",
                        "tableName":"jiazhengfuwuLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"家政服务收藏管理",
                        "menuJump":"列表",
                        "tableName":"jiazhengfuwuCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "订单",
                            "查看"
                        ],
                        "menu":"家政服务订单管理",
                        "menuJump":"列表",
                        "tableName":"jiazhengfuwuOrder"
                    }
                ],
                "menu":"家政服务管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"用户",
        "tableName":"yonghu"
    }
]
    }
}
export default menu;
